import { logger } from "@trigger.dev/sdk";

/**
 * When the recurring-invoice day runs, and how far ahead its warning looks.
 *
 * These two belong together, because the second is derived from the first.
 *
 * The warning window is `(now, now + LOOK_AHEAD]`, and the generation takes
 * everything with `nextScheduledAt <= now`. When the look-ahead equals the gap
 * between runs, consecutive windows tile the timeline exactly — no gap, no
 * overlap — so a series falls in exactly one of them, is warned there, and is
 * generated by the very next run. **The warning therefore always arrives one
 * run, which is to say one day, before the invoice goes out.** That is what
 * lets the email say "scheduled for tomorrow" and be right.
 *
 * Change the cron and this has to change with it, which is why
 * `recurring-invoice-day.test.ts` asserts they still agree.
 *
 * 05:00 UTC: after UTC midnight, so a series dated today is invoiced on the
 * same UTC day, and early enough to reach a European inbox in the morning.
 */
export const RECURRING_INVOICE_CRON = "0 5 * * *";

/** The gap between two fires of {@link RECURRING_INVOICE_CRON}. */
export const RECURRING_INVOICE_INTERVAL_HOURS = 24;

/**
 * How far ahead {@link RECURRING_INVOICE_CRON} warns.
 *
 * Two kinds of series get no warning, and did get one while this ran hourly:
 *
 * - one that falls due within a day of being created or edited — it is
 *   generated by the next run, which is also the first run that could have
 *   warned about it;
 * - one that recurs daily, for the same reason on every cycle.
 *
 * Both are the cadence, not a bug in the window: a run cannot warn a day ahead
 * about something that is less than a day away. Neither matters for a feature
 * whose unit is a month.
 */
export const WARNING_LOOK_AHEAD_HOURS = RECURRING_INVOICE_INTERVAL_HOURS;

/**
 * What the daily recurring-invoice run did, one half per job.
 *
 * `null` means that half failed. The run itself still succeeds when the
 * warning half fails, so the failure has to be legible in the output rather
 * than only in the thrown error of a run that did not happen.
 */
export interface RecurringInvoiceDayResult {
  warned: unknown;
  generated: unknown;
}

/** What `triggerAndWait` hands back, narrowed to what this needs of it. */
export type HalfResult =
  | { ok: true; output: unknown }
  | { ok: false; error: unknown };

/**
 * The order the two halves run in, and what happens when one of them fails.
 *
 * Separated from the task in `tasks/invoice/recurring-daily-scheduler.ts` so
 * that both rules can be tested without the Trigger runtime — they are the
 * whole point of folding two schedules into one.
 */
export async function runRecurringInvoiceDay(
  warn: () => Promise<HalfResult>,
  generate: () => Promise<HalfResult>,
): Promise<RecurringInvoiceDayResult> {
  // The warning goes first, so that within one run no series can be invoiced
  // before the notice that it was coming.
  const warning = await warn();

  if (!warning.ok) {
    // A warning that failed to send must not stop the invoice from being
    // generated — the invoice is the part the business depends on.
    logger.error("Upcoming-invoice warnings failed; generating anyway", {
      error: warning.error,
    });
  }

  const generation = await generate();

  if (!generation.ok) {
    logger.error("Recurring invoice generation failed", {
      error: generation.error,
    });
  }

  return {
    warned: warning.ok ? warning.output : null,
    generated: generation.ok ? generation.output : null,
  };
}
