ALTER POLICY "Team members can view their sync records" ON "accounting_sync_records" TO public USING ((team_id IN ( SELECT private.get_teams_for_authenticated_user() AS get_teams_for_authenticated_user)));--> statement-breakpoint
ALTER POLICY "Team members can update sync records" ON "accounting_sync_records" TO public USING ((team_id IN ( SELECT private.get_teams_for_authenticated_user() AS get_teams_for_authenticated_user))) WITH CHECK ((team_id IN ( SELECT private.get_teams_for_authenticated_user() AS get_teams_for_authenticated_user)));--> statement-breakpoint
ALTER POLICY "Apps can be inserted by a member of the team" ON "apps" TO public WITH CHECK ((team_id IN ( SELECT private.get_teams_for_authenticated_user() AS get_teams_for_authenticated_user)));--> statement-breakpoint
ALTER POLICY "Apps can be selected by a member of the team" ON "apps" TO public USING ((team_id IN ( SELECT private.get_teams_for_authenticated_user() AS get_teams_for_authenticated_user)));--> statement-breakpoint
ALTER POLICY "Apps can be updated by a member of the team" ON "apps" TO public USING ((team_id IN ( SELECT private.get_teams_for_authenticated_user() AS get_teams_for_authenticated_user))) WITH CHECK ((team_id IN ( SELECT private.get_teams_for_authenticated_user() AS get_teams_for_authenticated_user)));--> statement-breakpoint
ALTER POLICY "Bank Accounts can be deleted by a member of the team" ON "bank_accounts" TO public USING (((team_id IN ( SELECT private.get_teams_for_authenticated_user() AS get_teams_for_authenticated_user))));--> statement-breakpoint
ALTER POLICY "Bank Accounts can be selected by a member of the team" ON "bank_accounts" TO public USING (((team_id IN ( SELECT private.get_teams_for_authenticated_user() AS get_teams_for_authenticated_user))));--> statement-breakpoint
ALTER POLICY "Bank Accounts can be updated by a member of the team" ON "bank_accounts" TO public USING (((team_id IN ( SELECT private.get_teams_for_authenticated_user() AS get_teams_for_authenticated_user))));--> statement-breakpoint
ALTER POLICY "Bank Connections can be deleted by a member of the team" ON "bank_connections" TO public USING (((team_id IN ( SELECT private.get_teams_for_authenticated_user() AS get_teams_for_authenticated_user))));--> statement-breakpoint
ALTER POLICY "Bank Connections can be selected by a member of the team" ON "bank_connections" TO public USING (((team_id IN ( SELECT private.get_teams_for_authenticated_user() AS get_teams_for_authenticated_user))));--> statement-breakpoint
ALTER POLICY "Bank Connections can be updated by a member of the team" ON "bank_connections" TO public USING (((team_id IN ( SELECT private.get_teams_for_authenticated_user() AS get_teams_for_authenticated_user))));--> statement-breakpoint
ALTER POLICY "Documents can be updated by a member of the team" ON "documents" TO public USING ((team_id IN ( SELECT private.get_teams_for_authenticated_user() AS get_teams_for_authenticated_user))) WITH CHECK ((team_id IN ( SELECT private.get_teams_for_authenticated_user() AS get_teams_for_authenticated_user)));--> statement-breakpoint
ALTER POLICY "Enable insert for authenticated users only" ON "documents" TO authenticated WITH CHECK ((team_id IN ( SELECT private.get_teams_for_authenticated_user() AS get_teams_for_authenticated_user)));--> statement-breakpoint
ALTER POLICY "Inbox accounts can be selected by a member of the team" ON "inbox_accounts" TO public USING ((team_id IN ( SELECT private.get_teams_for_authenticated_user() AS get_teams_for_authenticated_user)));--> statement-breakpoint
ALTER POLICY "Inbox accounts can be updated by a member of the team" ON "inbox_accounts" TO public USING ((team_id IN ( SELECT private.get_teams_for_authenticated_user() AS get_teams_for_authenticated_user))) WITH CHECK ((team_id IN ( SELECT private.get_teams_for_authenticated_user() AS get_teams_for_authenticated_user)));--> statement-breakpoint
ALTER POLICY "Users can manage their own insight status" ON "insight_user_status" TO public USING ((user_id = auth.uid())) WITH CHECK ((user_id = auth.uid()));--> statement-breakpoint
ALTER POLICY "Reports can be deleted by a member of the team" ON "reports" TO public USING (((team_id IN ( SELECT private.get_teams_for_authenticated_user() AS get_teams_for_authenticated_user))));--> statement-breakpoint
ALTER POLICY "Reports can be selected by a member of the team" ON "reports" TO public USING (((team_id IN ( SELECT private.get_teams_for_authenticated_user() AS get_teams_for_authenticated_user))));--> statement-breakpoint
ALTER POLICY "Reports can be updated by member of team" ON "reports" TO public USING (((team_id IN ( SELECT private.get_teams_for_authenticated_user() AS get_teams_for_authenticated_user))));--> statement-breakpoint
ALTER POLICY "Invited users can select team if they are invited." ON "teams" TO public USING (((id IN ( SELECT private.get_invites_for_authenticated_user() AS get_invites_for_authenticated_user))));--> statement-breakpoint
ALTER POLICY "Teams can be deleted by a member of the team" ON "teams" TO public USING (((id IN ( SELECT private.get_teams_for_authenticated_user() AS get_teams_for_authenticated_user))));--> statement-breakpoint
ALTER POLICY "Teams can be selected by a member of the team" ON "teams" TO public USING (((id IN ( SELECT private.get_teams_for_authenticated_user() AS get_teams_for_authenticated_user))));--> statement-breakpoint
ALTER POLICY "Teams can be updated by a member of the team" ON "teams" TO public USING (((id IN ( SELECT private.get_teams_for_authenticated_user() AS get_teams_for_authenticated_user))));--> statement-breakpoint
ALTER POLICY "Entries can be deleted by a member of the team" ON "tracker_entries" TO authenticated USING (((team_id IN ( SELECT private.get_teams_for_authenticated_user() AS get_teams_for_authenticated_user))));--> statement-breakpoint
ALTER POLICY "Entries can be selected by a member of the team" ON "tracker_entries" TO authenticated USING (((team_id IN ( SELECT private.get_teams_for_authenticated_user() AS get_teams_for_authenticated_user))));--> statement-breakpoint
ALTER POLICY "Entries can be updated by a member of the team" ON "tracker_entries" TO authenticated USING ((team_id IN ( SELECT private.get_teams_for_authenticated_user() AS get_teams_for_authenticated_user))) WITH CHECK (((team_id IN ( SELECT private.get_teams_for_authenticated_user() AS get_teams_for_authenticated_user))));--> statement-breakpoint
ALTER POLICY "Projects can be deleted by a member of the team" ON "tracker_projects" TO authenticated USING (((team_id IN ( SELECT private.get_teams_for_authenticated_user() AS get_teams_for_authenticated_user))));--> statement-breakpoint
ALTER POLICY "Projects can be selected by a member of the team" ON "tracker_projects" TO authenticated USING (((team_id IN ( SELECT private.get_teams_for_authenticated_user() AS get_teams_for_authenticated_user))));--> statement-breakpoint
ALTER POLICY "Projects can be updated by a member of the team" ON "tracker_projects" TO authenticated USING (((team_id IN ( SELECT private.get_teams_for_authenticated_user() AS get_teams_for_authenticated_user))));--> statement-breakpoint
ALTER POLICY "Transaction Attachments can be deleted by a member of the team" ON "transaction_attachments" TO public USING (((team_id IN ( SELECT private.get_teams_for_authenticated_user() AS get_teams_for_authenticated_user))));--> statement-breakpoint
ALTER POLICY "Transaction Attachments can be selected by a member of the team" ON "transaction_attachments" TO public USING (((team_id IN ( SELECT private.get_teams_for_authenticated_user() AS get_teams_for_authenticated_user))));--> statement-breakpoint
ALTER POLICY "Transaction Attachments can be updated by a member of the team" ON "transaction_attachments" TO public USING (((team_id IN ( SELECT private.get_teams_for_authenticated_user() AS get_teams_for_authenticated_user))));--> statement-breakpoint
ALTER POLICY "Enable update for authenticated users only" ON "transaction_enrichments" TO authenticated WITH CHECK ((true));--> statement-breakpoint
ALTER POLICY "User Invites can be created by a member of the team" ON "user_invites" TO public WITH CHECK (((team_id IN ( SELECT private.get_teams_for_authenticated_user() AS get_teams_for_authenticated_user))));--> statement-breakpoint
ALTER POLICY "User Invites can be deleted by a member of the team" ON "user_invites" TO public USING (((team_id IN ( SELECT private.get_teams_for_authenticated_user() AS get_teams_for_authenticated_user))));--> statement-breakpoint
ALTER POLICY "User Invites can be deleted by invited email" ON "user_invites" TO public USING ((((auth.jwt() ->> 'email'::text) = email)));--> statement-breakpoint
ALTER POLICY "User Invites can be selected by a member of the team" ON "user_invites" TO public USING (((team_id IN ( SELECT private.get_teams_for_authenticated_user() AS get_teams_for_authenticated_user))));--> statement-breakpoint
ALTER POLICY "User Invites can be updated by a member of the team" ON "user_invites" TO public USING (((team_id IN ( SELECT private.get_teams_for_authenticated_user() AS get_teams_for_authenticated_user))));--> statement-breakpoint
ALTER POLICY "Users can select their own profile." ON "users" TO public USING (((auth.uid() = id)));--> statement-breakpoint
ALTER POLICY "Users can select users if they are in the same team" ON "users" TO authenticated USING (((EXISTS ( SELECT 1 FROM public.users_on_team WHERE ((users_on_team.user_id = ( SELECT auth.uid() AS uid)) AND (users_on_team.team_id = users.team_id))))));--> statement-breakpoint
ALTER POLICY "Users can update own profile." ON "users" TO public USING (((auth.uid() = id)));--> statement-breakpoint
ALTER POLICY "Enable updates for users on team" ON "users_on_team" TO authenticated USING (((team_id IN ( SELECT private.get_teams_for_authenticated_user() AS get_teams_for_authenticated_user)))) WITH CHECK (((team_id IN ( SELECT private.get_teams_for_authenticated_user() AS get_teams_for_authenticated_user))));--> statement-breakpoint
ALTER POLICY "Select for current user teams" ON "users_on_team" TO authenticated USING ((team_id IN ( SELECT private.get_teams_for_authenticated_user() AS get_teams_for_authenticated_user)));--> statement-breakpoint
ALTER POLICY "Users on team can be deleted by a member of the team" ON "users_on_team" TO public USING (((team_id IN ( SELECT private.get_teams_for_authenticated_user() AS get_teams_for_authenticated_user))));